# OSX/Linux (https://github.com/travis-ci-tester/toolchain-table)

# Original: https://github.com/forexample/hunter-simple/blob/master/.travis.yml

language:
  - cpp

# Container-based infrastructure (Linux)
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F
sudo:
  - false

dist:
  - trusty

# Install packages differs for container-based infrastructure
# * https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # For off screen rendering
      - libegl1-mesa-dev
      - libosmesa6-dev

      # xorg-macros: https://github.com/BlueDragonX/xf86-input-mtrack/issues/27#issuecomment-186871891
      - xutils-dev
      - xserver-xorg-dev-lts-trusty

      # Packages for Android development: http://superuser.com/a/360398/252568
      - libncurses5:i386
      - libstdc++6:i386
      - zlib1g:i386

      # Default GCC 4.8 is buggy:
      # * https://github.com/elucideye/drishti/issues/273#issuecomment-301297286
      #- g++-5
      #- gcc-5

env:
  global:
    - secure: "UW9uugVbUDdGwngqj69XFNkdrAo1xKZZo+XI/Aw+UsH2+f/bpsn4XAiy/o5Wn0RESpDdYKr4hWJsvBvuBAt43MFsLojgQcA6O0bmds8jCX6iNlspUJF1VfPysF40kscUH2jpobU23vQ4NV9aPZ8bK53KGUghfIB4j8iv84lD7CgYP7rI/pJAuQip3oGQNNR4LiO204FwzJkhSexmWKFMBc3gPD2Z7jGwQVzkZsO2oAZF101wqxDUxcoTBggq5zTEZL5OhoZuLRzk1t08I7L3P+N3jyqzgGr9RuzDUIZceR1KnyqegI2ij2vbFklIinxqiLkZnRWAXRhtScq2te9Sfj53CDrHg9F3FcTK9Bb1vgwCCXHqrOsmdHdsxWLU8iwqRDGD9JZj4s16MqeHkJapKDxf+ptS5c35UHN+J30fBhOHMGshhLFQTbfLzPChDliT+/tHqa3cFtO8M3FxBhuUiV5FBbMrSrGTTjqb1UrTCMZOKC1G90sUCVVGILMiji3I67h0+EE/WE53XHuGJven/+cZxRq8p4xqnDHlCmyKKbdJf6K5RULTL11fJcgHuWXoUn3tmYNWsPbtgSu2dAl0E40/LsF4uvBLzp/23a89l4lo2FH1+btpjN8SeJAhX0Qwwp1tSB1s2YrbdOtMhOqBQ0jvtgv4bjAbLpYhUgXGCrA="

matrix:
  include:
    # Linux {

    - os: linux
      env: CONFIG=Release TOOLCHAIN=gcc INSTALL=--strip MESA=ON TEST=--test

    # }

    # OSX {

    # Try to match toolchains from ingenue deep tests to improve cache hits:
    # https://github.com/ingenue/hunter/blob/pkg.opencv/.travis.yml

    - os: osx
      env: CONFIG=Release TOOLCHAIN=ios-nocodesign-9-3-arm64 INSTALL=--install MESA=OFF

    - os: osx
      env: CONFIG=Release TOOLCHAIN=osx-10-11 INSTALL=--install MESA=OFF

    - os: osx
      env: CONFIG=Release TOOLCHAIN=android-ndk-r10e-api-19-armeabi-v7a-neon INSTALL=--strip MESA=OFF TEST=--test

    # }

before_install:

  # Add '--quiet' to avoid leaking the token to logs
  - git submodule update --init --recursive --quiet

install:
  # Info about OS
  - uname -a

  # Install Python 3
  - if [[ "`uname`" == "Darwin" ]]; then travis_retry brew install python3; fi

  # Install Python package 'requests'
  # 'easy_install3' is not installed by 'brew install python3' on OS X 10.9 Maverick
  - if [[ "`uname`" == "Darwin" ]]; then pip3 install requests; fi
  - if [[ "`uname`" == "Linux" ]]; then travis_retry pip3 install --user requests; fi

  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_ROOT="`pwd`/polly-master"
  - export PATH="${POLLY_ROOT}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py

  # Tune locations
  - export PATH="`pwd`/_ci/cmake/bin:${PATH}"

  # Installed if toolchain is Android (otherwise directory doesn't exist)
  - export ANDROID_NDK_r10e="`pwd`/_ci/android-ndk-r10e"

script:

  - >
    polly.py
    --toolchain ${TOOLCHAIN}
    --config ${CONFIG}
    --verbose
    --ios-multiarch --ios-combined
    --fwd HUNTER_CONFIGURATION_TYPES=${CONFIG}
    OGLES_GPGPU_BUILD_TESTS=ON
    OGLES_GPGPU_USE_OSMESA=${MESA}
    GAUZE_ANDROID_USE_EMULATOR=YES
    HUNTER_CONFIGURATION_TYPES=${CONFIG}
    HUNTER_SUPPRESS_LIST_OF_FILES=ON
    --jobs 2
    ${INSTALL} ${TEST}

  # Upload to server
  - git clone https://github.com/ruslo/hunter
  - >
    ./hunter/maintenance/upload-cache-to-github.py
    --username ingenue
    --repo-owner ingenue
    --repo hunter-cache
    --cache-dir ${HOME}/.hunter/_Base/Cache
    --temp-dir ${HOME}/__TEMP_HUNTER

branches:
  except:
    - /^pr\..*/
